moveit: update to 0.9.12
moveit: adjust linelicense and wip!

moveit: multiple adjustments

  - update SRCURI hash
  - adjust directory
  - make all recipes with version 0.9.6
  - adjust license line number
  - drop patch 0001-Fix-conversion-of-shared-ptr-to-bool-for-C-11.patch, as it can be reverse-applied

moveit: updating to 0.9.9

moveit-ros-perception: adjust patches for kinetic version

moveit: update to 0.9.11

moveit: fix license lines

moveit-ros-perception: include further patch

moveit: update to 0.9.12

moveit: fixup

moveit: another fixup

moveit-ros-planning: add missing dependency on tf-conversions

* fixes:
  ERROR: moveit-ros-planning-0.7.13-r0 do_package_qa: QA Issue: /opt/ros/indigo/lib/libmoveit_planning_scene_monitor.so.0.7.3 contained in package moveit-ros-planning requires libtf_conversions.so()(64bit), but no providers found in RDEPENDS_moveit-ros-planning? [file-rdeps]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

moveit-core: fixup after rebase: drop backported patch