{eloquent} cv-bridge: add missing dependency
* fixes:
  | -- Found PythonInterp: /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/cv-bridge/2.1.3-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found version "3.7.2")
  | -- Found PythonLibs: /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/cv-bridge/2.1.3-1-r0/recipe-sysroot/usr/lib/libpython3.7m.so (found suitable version "3.7.2", minimum required is "3.7")
  | Traceback (most recent call last):
  |   File "<string>", line 1, in <module>
  | ModuleNotFoundError: No module named 'numpy'
  | CMake Error at src/CMakeLists.txt:34 (message):
  |   Could not determine the NumPy include directory, verify that NumPy was
  |   installed correctly.
  |
  |
  | -- Configuring incomplete, errors occurred!
  | See also "/jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/cv-bridge/2.1.3-1-r0/build/CMakeFiles/CMakeOutput.log".
  | WARNING: exit code 1 from a shell command.
  | ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-mcf-herb/artifacts/BUILD-ros2-eloquent-thud.mcf/work/i586-oe-linux/cv-bridge/2.1.3-1-r0/temp/log.do_configure.3451)
  ERROR: Task (/jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/generated-recipes/vision-opencv/cv-bridge_2.1.3-1.bb:do_configure) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>