{eloquent} rosidl-typesupport-fastrtps-c: add missing dependencies
ERROR: rosidl-typesupport-fastrtps-c-0.8.0-1-r0 do_configure: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/temp/log.do_configure.45220)
ERROR: Logfile of failure stored in: /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/temp/log.do_configure.45220
Log data follows:
| DEBUG: Executing shell function do_configure
| -- The C compiler identification is GNU 8.2.0
| -- The CXX compiler identification is GNU 8.2.0
| -- Check for working C compiler: /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-gcc
| -- Check for working C compiler: /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-gcc -- works
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Check for working CXX compiler: /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-g++
| -- Check for working CXX compiler: /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-g++ -- works
| -- Detecting CXX compiler ABI info
| -- Detecting CXX compiler ABI info - done
| -- Detecting CXX compile features
| -- Detecting CXX compile features - done
| -- Found ament_cmake: 0.8.1 (/jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake/cmake)
| -- Found PythonInterp: /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.7.2", minimum required is "3")
| -- Using PYTHON_EXECUTABLE: /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
| -- Found fastrtps_cmake_module: 0.8.0 (/jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/recipe-sysroot-native/usr/share/fastrtps_cmake_module/cmake)
| CMake Error at CMakeLists.txt:30 (find_package):
|   Could not find a configuration file for package "fastcdr" that is
|   compatible with requested version "".
|
|   The following configuration files were considered but not accepted:
|
|     /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/recipe-sysroot-native/usr/share/fastcdr/cmake/fastcdr-config.cmake, version: 1.0.10 (64bit)
|
|
|
| -- Configuring incomplete, errors occurred!
| See also "/jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/build/CMakeFiles/CMakeOutput.log".
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /jenkins/mjansa/build-ros-thud-eloquent/BUILD/work/cortexa7t2hf-neon-vfpv4-oe-linux-gnueabi/rosidl-typesupport-fastrtps-c/0.8.0-1-r0/temp/log.do_configure.45220)
NOTE: recipe rosidl-typesupport-fastrtps-c-0.8.0-1-r0: task do_configure: Failed
ERROR: Task (/jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/rosidl-typesupport-fastrtps/rosidl-typesupport-fastrtps-c_0.8.0-1.bb:do_configure) failed with exit code '1'

Signed-off-by: Martin Jansa <martin.jansa@lge.com>