python-catkin-pkg: Fix missing module
Error was:

File "/opt/ros/melodic/lib/python2.7/site-packages/catkin/find_in_workspaces.py"
    from catkin_pkg.packages import find_packages
ImportError: No module named catkin_pkg.packages